package steve6472.flare.pipeline;

import steve6472.flare.ShaderSPIRVUtils;
import steve6472.flare.pipeline.builder.PipelineBuilder;
import steve6472.flare.pipeline.builder.PipelineConstructor;
import steve6472.flare.settings.VisualSettings;
import steve6472.flare.struct.def.Push;
import steve6472.flare.struct.def.Vertex;

import static org.lwjgl.vulkan.VK10.*;

/**
 * Created by steve6472
 * Date: 9/1/2024
 * Project: Flare <br>
 */
public interface Pipelines
{
    PipelineConstructor BLOCKBENCH_STATIC = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/blockbench_static.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/blockbench_static.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.POS3F_NORMAL_UV)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .depthStencil()
            .depthEnableFlags(true, true)
            .depthCompareOp(VK_COMPARE_OP_LESS)
            .bounds(0.0f, 1.0f, false)
            .stencilTestEnable(false)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, false)
            .done()
        .pushConstants()
            .constant(VK_SHADER_STAGE_VERTEX_BIT, 0, Push.STATIC_TRANSFORM_OFFSET.sizeof())
            .done()
        .build(renderPass, setLayouts);

    PipelineConstructor DEBUG_LINE = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/debug_line.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/debug_line.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.POS3F_COL4F)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_LINE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .lineWidth(VisualSettings.ENABLE_WIDE_LINES.get() ? VisualSettings.LINE_WIDTH.get() : 1.0f)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .depthStencil()
            .depthEnableFlags(true, true)
            .depthCompareOp(VK_COMPARE_OP_LESS_OR_EQUAL)
            .bounds(0.0f, 1.0f, false)
            .stencilTestEnable(false)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, false)
            .done()
        .pushConstants()
            .done()
        .build(renderPass, setLayouts);


    PipelineConstructor UI_DEBUG_LINE = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/debug_line.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/debug_line.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.POS3F_COL4F)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_LINE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .lineWidth(1.0f)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .depthStencil()
            .depthEnableFlags(true, true)
            .depthCompareOp(VK_COMPARE_OP_LESS_OR_EQUAL)
            .bounds(0.0f, 1.0f, false)
            .stencilTestEnable(false)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, false)
            .done()
        .pushConstants()
            .done()
        .build(renderPass, setLayouts);

    PipelineConstructor FONT_BITMAP = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/font_bitmap.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/font_bitmap.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.POS3F_COL4F_UV)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .lineWidth(1.0f)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .depthStencil()
            .depthEnableFlags(true, true)
            .depthCompareOp(VK_COMPARE_OP_LESS)
            .bounds(0.0f, 1.0f, false)
            .stencilTestEnable(false)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, true)
            .done()
        .pushConstants()
            .done()
        .build(renderPass, setLayouts);

    PipelineConstructor FONT_SDF = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/font_sdf.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/font_sdf.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.POS3F_UV_INDEX)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .lineWidth(1.0f)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .depthStencil()
            .depthEnableFlags(true, true)
            .depthCompareOp(VK_COMPARE_OP_LESS_OR_EQUAL)
            .bounds(0.0f, 1.0f, false)
            .stencilTestEnable(false)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, true)
            .done()
        .pushConstants()
            .done()
        .build(renderPass, setLayouts);

    PipelineConstructor UI_TEXTURE = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/ui_texture.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/ui_texture.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.POS3F_COL3F_DATA3F)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .lineWidth(1.0f)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .depthStencil()
            .depthEnableFlags(true, true)
            .depthCompareOp(VK_COMPARE_OP_LESS)
            .bounds(0.0f, 1.0f, false)
            .stencilTestEnable(false)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, true)
            .done()
        .pushConstants()
            .done()
        .build(renderPass, setLayouts);

    PipelineConstructor ATLAS_ANIMATION = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/atlas_animation.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/atlas_animation.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.POS3F_DATA3F)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .lineWidth(1.0f)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, true)
            .done()
        .pushConstants()
            .done()
        .build(renderPass, setLayouts);

    PipelineConstructor SKIN = (device, extent, renderPass, setLayouts) -> PipelineBuilder
        .create(device)
        .shaders()
            .addShader(ShaderSPIRVUtils.ShaderKind.VERTEX_SHADER, "flare/shaders/skin.vert", VK_SHADER_STAGE_VERTEX_BIT)
            .addShader(ShaderSPIRVUtils.ShaderKind.FRAGMENT_SHADER, "flare/shaders/skin.frag", VK_SHADER_STAGE_FRAGMENT_BIT)
            .done()
        .vertexInputInfo(Vertex.SKIN)
        .inputAssembly(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, false)
        .viewport()
            .viewportBounds(0.0f, extent.height(), extent.width(), -extent.height())
            .viewportDepths(0.0f, 1.0f)
            .scissorOffset(0, 0)
            .scissorExtent(extent)
            .done()
        .rasterization()
            .flags(false, false, false)
            .polygonInfo(VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_COUNTER_CLOCKWISE)
            .done()
        .multisampling()
            .sampleShading(false)
            .rasterizationSamples(VK_SAMPLE_COUNT_1_BIT)
            .done()
        .depthStencil()
            .depthEnableFlags(true, true)
            .depthCompareOp(VK_COMPARE_OP_LESS)
            .bounds(0.0f, 1.0f, false)
            .stencilTestEnable(false)
            .done()
        .colorBlend(true, VK_LOGIC_OP_COPY, 0f, 0f, 0f, 0f)
            .attachment(VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT, false)
            .done()
        .pushConstants()
            .constant(VK_SHADER_STAGE_VERTEX_BIT, 0, Push.SKIN)
            .done()
        .build(renderPass, setLayouts);
}
